name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-Xmx4g -Xms512m -Dfile.encoding=UTF-8"
      GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx4g -Xms512m -Dfile.encoding=UTF-8'"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'     # Loom 1.11.x требует 21

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.14   # совместимо с Loom 1.11.x

      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 8.14

      - name: Build
        run: ./gradlew clean build --no-daemon --refresh-dependencies --stacktrace --info

      - uses: actions/upload-artifact@v4
        with:
          name: neoseoul-dokkebi
          path: build/libs/*.jar
