name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # дубль на всякий случай — задаём память ещё и через окружение
      JAVA_TOOL_OPTIONS: "-Xmx3g -Xms512m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8"
      GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx3g -Xms512m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8'"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2

      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 8.2

      - name: Build (no daemon, refresh deps)
        run: ./gradlew clean build --no-daemon --refresh-dependencies --stacktrace --info

      - uses: actions/upload-artifact@v4
        with:
          name: neoseoul-dokkebi
          path: build/libs/*.jar
